/* mbed Microcontroller Library
 * Copyright (c) 2024 ARM Limited
 * SPDX-License-Identifier: Apache-2.0
 */

#include "PeripheralPins.h"
#include "mbed_toolchain.h"
#include "r_adc_api.h"
#include "r_dac_api.h"
#include "r_ioport.h"

//*** ADC ***

const PinMap PinMap_ADC[] = {
    {P0_0, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_0)},
    {P0_1, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_1)},
    {P0_2, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_2)},
    {P0_3, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_7)},
    {P0_4, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_4)},
    {P0_5, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_5)},
    {P0_6, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_6)},
    {P0_8, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_8)},
    {P0_13, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_11)},
    {P0_14, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_12)},
    {P0_15, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_13)},
    {P5_0, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_16)},
    {NC, NC, 0}
};

//*** DAC ***

const PinMap PinMap_DAC[] = {
    {P0_14, DAC_0, RA_PIN_DATA(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0)},
    {P0_15, DAC_1, RA_PIN_DATA(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0)},
    {NC, NC, 0}
};

//*** PWM ***

const PinMap PinMap_PWM[] = {
    {P1_0, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_1, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_2, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_2, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_3, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    // {P1_4, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    // {P1_5, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_6, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P1_7, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_8, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_9, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    // {P1_9, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_10, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    // {P1_10, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_11, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_12, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_12, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_13, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_5, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P2_5, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_6, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_7, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_12, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_13, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P3_0, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P3_1, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P3_2, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_3, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_8, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    // {P4_8, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_9, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    // {P4_9, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P5_0, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P8_14, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P8_15, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {NC, NC, 0}
};

//*** IRQ ***

const PinMap PinMap_IRQ[] = {
    {P1_5, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_0, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_1, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_4, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_0, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_13, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_10, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_12, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_11, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_11, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_2, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_10, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_1, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_9, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_8, IRQ_7, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_4, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_15, IRQ_13, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_6, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_5, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_2, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_1, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_0, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_1, IRQ_7, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_2, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_4, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_5, IRQ_10, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_6, IRQ_11, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_8, IRQ_12, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_3, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {NC, NC, 0}
};

// SERIAL

const PinMap PinMap_UART_RX[] = {
    {P1_0, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P1_10, UART_9, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P2_12, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P4_10, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {NC, NC, 0}
};

const PinMap PinMap_UART_TX[] = {
    {P1_1, UART_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P1_9, UART_9, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P2_13, UART_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P4_11, UART_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {NC, NC, 0}
};

// SPI

const PinMap PinMap_SPI_MOSI[] = {
    {P1_9, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P2_7, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P1_1, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {NC, NC, 0}
};

const PinMap PinMap_SPI_MISO[] = {
    {P1_10, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P2_6, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_0, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {NC, NC, 0}
};

const PinMap PinMap_SPI_SCLK[] = {
    {P1_11, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P3_2, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P1_2, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {NC, NC, 0}
};

const PinMap PinMap_SPI_SSEL[] = {
    {P1_7, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_8, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_12, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P2_5, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P3_0, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P3_1, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_3, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_4, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_5, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_6, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {NC, NC, 0}
};

// I2C

const PinMap PinMap_I2C_SCL[] = {
    {P1_0, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P2_5, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_0, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_8, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {NC, NC, 0}
};

const PinMap PinMap_I2C_SDA[] = {
    {P1_1, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P2_6, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_1, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_7, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {NC, NC, 0}
};

// CAN

const PinMap PinMap_CAN_RD[] = {
    {P1_2, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P1_10, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P4_2, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {NC, NC, 0}
};

const PinMap PinMap_CAN_TD[] = {
    {P1_3, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P1_9, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P4_1, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {NC, NC, 0}
};
