/* Copyright (c) 2024 Renesas Electronics Corporation
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* generated pin source file - do not edit */
#include "bsp_api.h"
#include "r_ioport.h"

/* SDRAM pins of the CPKHMI-RA8P1 (2 x Winbond W9812G2KB, 32-bit bus,
 * 16 MB at 0x68000000). These are configured by R_IOPORT_Open() from
 * R_BSP_WarmStart(BSP_WARM_START_POST_C), before R_BSP_SdramInit().
 * Pin assignment taken from the official CPKHMI-RA8P1 SDRAM example. */
const ioport_pin_cfg_t g_bsp_pin_cfg_data[] = {
    /* Address (A0/A1 share pins with DQM1/DQM3) */
    { .pin = BSP_IO_PORT_10_PIN_05, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A0/DQM1 */
    { .pin = BSP_IO_PORT_10_PIN_04, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A1/DQM3 */
    { .pin = BSP_IO_PORT_10_PIN_03, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A2 */
    { .pin = BSP_IO_PORT_10_PIN_02, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A3 */
    { .pin = BSP_IO_PORT_10_PIN_01, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A4 */
    { .pin = BSP_IO_PORT_10_PIN_00, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A5 */
    { .pin = BSP_IO_PORT_05_PIN_03, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A6 */
    { .pin = BSP_IO_PORT_05_PIN_04, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A7 */
    { .pin = BSP_IO_PORT_05_PIN_05, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A8 */
    { .pin = BSP_IO_PORT_05_PIN_06, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A9 */
    { .pin = BSP_IO_PORT_05_PIN_07, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A10 */
    { .pin = BSP_IO_PORT_05_PIN_08, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A11 */
    { .pin = BSP_IO_PORT_05_PIN_09, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A12 */
    { .pin = BSP_IO_PORT_05_PIN_10, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A13 */
    { .pin = BSP_IO_PORT_06_PIN_08, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A14 */
    { .pin = BSP_IO_PORT_13_PIN_00, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM A15 */
    /* Control and byte-lane masks */
    { .pin = BSP_IO_PORT_08_PIN_13, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM SDCS */
    { .pin = BSP_IO_PORT_10_PIN_06, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM CKE */
    { .pin = BSP_IO_PORT_10_PIN_15, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM SDCLK */
    { .pin = BSP_IO_PORT_10_PIN_10, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM RAS */
    { .pin = BSP_IO_PORT_10_PIN_09, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM CAS */
    { .pin = BSP_IO_PORT_10_PIN_08, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM WE */
    { .pin = BSP_IO_PORT_06_PIN_14, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQM0 */
    { .pin = BSP_IO_PORT_06_PIN_15, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQM2 */
    /* Data DQ0-15 */
    { .pin = BSP_IO_PORT_03_PIN_02, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ0 */
    { .pin = BSP_IO_PORT_03_PIN_01, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ1 */
    { .pin = BSP_IO_PORT_03_PIN_00, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ2 */
    { .pin = BSP_IO_PORT_01_PIN_12, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ3 */
    { .pin = BSP_IO_PORT_01_PIN_13, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ4 */
    { .pin = BSP_IO_PORT_01_PIN_14, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ5 */
    { .pin = BSP_IO_PORT_01_PIN_15, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ6 */
    { .pin = BSP_IO_PORT_06_PIN_09, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ7 */
    { .pin = BSP_IO_PORT_10_PIN_11, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ8 */
    { .pin = BSP_IO_PORT_10_PIN_12, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ9 */
    { .pin = BSP_IO_PORT_10_PIN_13, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ10 */
    { .pin = BSP_IO_PORT_10_PIN_14, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ11 */
    { .pin = BSP_IO_PORT_06_PIN_10, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ12 */
    { .pin = BSP_IO_PORT_06_PIN_11, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ13 */
    { .pin = BSP_IO_PORT_06_PIN_12, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ14 */
    { .pin = BSP_IO_PORT_06_PIN_13, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ15 */
    /* Data DQ16-31 */
    { .pin = BSP_IO_PORT_12_PIN_14, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ16 */
    { .pin = BSP_IO_PORT_12_PIN_13, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ17 */
    { .pin = BSP_IO_PORT_12_PIN_12, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ18 */
    { .pin = BSP_IO_PORT_12_PIN_11, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ19 */
    { .pin = BSP_IO_PORT_12_PIN_10, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ20 */
    { .pin = BSP_IO_PORT_12_PIN_09, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ21 */
    { .pin = BSP_IO_PORT_12_PIN_08, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ22 */
    { .pin = BSP_IO_PORT_12_PIN_07, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ23 */
    { .pin = BSP_IO_PORT_12_PIN_06, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ24 */
    { .pin = BSP_IO_PORT_12_PIN_05, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ25 */
    { .pin = BSP_IO_PORT_12_PIN_04, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ26 */
    { .pin = BSP_IO_PORT_12_PIN_03, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ27 */
    { .pin = BSP_IO_PORT_12_PIN_02, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ28 */
    { .pin = BSP_IO_PORT_12_PIN_01, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ29 */
    { .pin = BSP_IO_PORT_12_PIN_00, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ30 */
    { .pin = BSP_IO_PORT_06_PIN_07, .pin_cfg = IOPORT_CFG_PERIPHERAL_PIN | IOPORT_CFG_DRIVE_HIGH | IOPORT_PERIPHERAL_BUS }, /* SDRAM DQ31 */
};

const ioport_cfg_t g_bsp_pin_cfg = {
    .number_of_pins = sizeof(g_bsp_pin_cfg_data) / sizeof(g_bsp_pin_cfg_data[0]),
    .p_pin_cfg_data = g_bsp_pin_cfg_data,
};