/* mbed Microcontroller Library
 *******************************************************************************
 * Copyright (c) 2018, STMicroelectronics
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of STMicroelectronics nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************
 */

#include "PeripheralPins.h"
#include "mbed_toolchain.h"
#include "r_adc_api.h"
#include "r_dac_api.h"
#include "r_ioport.h"

//*** ADC ***

const PinMap PinMap_ADC[] = {
    {P0_0, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_0)},
    {P0_1, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_1)},
    {P0_2, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_2)},
    {P0_3, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_4)},
    {P0_4, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_0)},
    {P0_5, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_1)},
    {P0_6, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_2)},
    {P0_7, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_4)},
    {P0_8, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_8)},
    {P0_9, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_6)},
    {P0_10, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_5)},
    {P0_14, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_7)},
    {P0_15, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_5)},
    {NC, NC, 0}
};

//*** DAC ***

const PinMap PinMap_DAC[] = {
    {P0_14, DAC_0, RA_PIN_DATA(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0)},
    {NC, NC, 0}
};

//*** PWM ***

const PinMap PinMap_PWM[] = {
    {P1_2, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_2, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_3, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_4, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_5, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_6, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P1_7, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_12, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_13, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_14, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_15, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_2, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_3, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_4, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_5, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P2_5, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_8, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_9, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_10, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_11, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_12, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_13, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P3_0, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P3_1, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P3_2, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P3_11, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P3_12, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P4_3, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_4, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_5, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_6, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_7, PWM_GPT10, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_8, PWM_GPT10, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_10, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P4_11, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P4_14, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_15, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P5_11, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P5_12, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P6_9, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P6_10, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P6_11, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P6_13, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P6_14, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P7_0, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P7_1, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P7_3, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P7_4, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P7_12, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P7_12, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P7_13, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P7_13, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P8_0, PWM_GPT11, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P8_0, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P8_1, PWM_GPT11, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P8_1, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P8_2, PWM_GPT12, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P8_3, PWM_GPT12, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P8_4, PWM_GPT13, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P8_8, PWM_GPT13, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {NC, NC, 0}
};

//*** IRQ ***

const PinMap PinMap_IRQ[] = {
    {P1_5, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_0, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_6, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_1, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_4, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_0, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_13, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_8, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_12, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_0, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_11, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_2, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_10, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_1, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_9, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_8, IRQ_7, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_5, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_15, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P9_5, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_4, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_14, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P7_9, IRQ_10, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P7_8, IRQ_11, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_0, IRQ_11, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_1, IRQ_12, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_15, IRQ_13, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_10, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P5_12, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_4, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P5_11, IRQ_15, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_8, IRQ_15, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_6, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_5, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_3, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_2, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_2, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_1, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_0, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_1, IRQ_7, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_2, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_4, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_5, IRQ_10, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_6, IRQ_11, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_8, IRQ_12, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_9, IRQ_13, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_3, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_4, IRQ_15, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {NC, NC, 0}
};

//*** SERIAL ***

const PinMap PinMap_UART_RX[] = {
    {P1_1, UART_9, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P1_13, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P2_6, UART_4, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P2_8, UART_9, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P2_12, UART_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P3_9, UART_3, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P4_1, UART_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P4_8, UART_3, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P4_14, UART_4, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P6_2, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P6_10, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P7_0, UART_2, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P8_2, UART_2, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {NC, NC, 0}
};

const PinMap PinMap_UART_TX[] = {
    {P1_2, UART_9, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P1_12, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P2_5, UART_4, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P2_9, UART_9, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P2_13, UART_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P3_10, UART_3, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P4_0, UART_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P4_6, UART_2, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P4_9, UART_3, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P4_15, UART_4, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P6_3, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P6_9, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P8_1, UART_2, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {NC, NC, 0}
};

//*** SPI ***

const PinMap PinMap_SPI_MOSI[] = {
    {P1_15, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P2_2, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P6_11, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P7_1, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_1, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_11, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {NC, NC, 0}
};

const PinMap PinMap_SPI_MISO[] = {
    {P3_13, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P6_9, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P7_0, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_0, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_10, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {NC, NC, 0}
};

const PinMap PinMap_SPI_SCLK[] = {
    {P2_3, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P6_10, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P7_2, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_2, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_12, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {NC, NC, 0}
};

const PinMap PinMap_SPI_SSEL[] = {
    {P1_12, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_13, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_14, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P2_4, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P2_5, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P2_6, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P3_0, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_6, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_7, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P6_12, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P7_3, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P7_4, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P7_5, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_3, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_4, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_5, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_6, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_13, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_14, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_15, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P7_8, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {NC, NC, 0}
};

//*** I2C ***

const PinMap PinMap_I2C_SCL[] = {
    {P2_5, I2C_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC)},
    {P4_8, I2C_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC)},
    {P4_10, I2C_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC)},
    {P5_12, I2C_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC)},
    {NC, NC, 0}
};

const PinMap PinMap_I2C_SDA[] = {
    {P2_6, I2C_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC)},
    {P4_7, I2C_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC)},
    {P4_9, I2C_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC)},
    {P5_11, I2C_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC)},
    {NC, NC, 0}
};

//*** CAN  ***

const PinMap PinMap_CAN_RD[] = {
    {P1_2, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P2_2, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P2_8, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P3_11, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P4_2, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P4_14, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P5_11, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P6_10, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P7_5, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P8_14, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {NC, NC, 0}
};

const PinMap PinMap_CAN_TD[] = {
    {P1_3, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P2_3, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P2_9, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P3_12, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P4_1, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P4_15, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P5_12, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P6_9, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P7_4, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P8_15, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {NC, NC, 0}
};
