/* mbed Microcontroller Library
 * Copyright (c) 2024 ARM Limited
 * SPDX-License-Identifier: Apache-2.0
 */

#include "PeripheralPins.h"
#include "mbed_toolchain.h"
#include "r_adc_api.h"
#include "r_dac_api.h"
#include "r_ioport.h"

//*** ADC ***

const PinMap PinMap_ADC[] = {
    {P0_0, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_0)},
    {P0_0, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_0)},
    {P0_1, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_1)},
    {P0_1, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_1)},
    {P0_2, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_2)},
    {P0_2, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_2)},
    {P0_3, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_3)},
    {P0_4, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_4)},
    {P0_5, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_5)},
    {P0_6, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_6)},
    {P0_7, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_7)},
    {P0_8, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_8)},
    {P0_9, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_9)},
    {P0_10, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_10)},
    {P0_14, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_12)},
    {P0_15, ADC_0, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_13)},
    {P5_0, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_16)},
    {P5_1, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_17)},
    {P5_2, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_18)},
    {P5_3, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_19)},
    {P5_4, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_20)},
    {P5_5, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_21)},
    {P5_6, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_22)},
    {P5_7, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_23)},
    {P5_8, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_24)},
    {P8_0, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_25)},
    {P8_1, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_26)},
    {P8_2, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_27)},
    {P8_3, ADC_1, RA_PIN_DATA_EXT(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0, ADC_CHANNEL_28)},
    {NC, NC, 0}
};

//*** DAC ***

const PinMap PinMap_DAC[] = {
    {P0_14, DAC_0, RA_PIN_DATA(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0)},
    {P0_15, DAC_1, RA_PIN_DATA(RA_PIN_MODE_ANALOG, RA_PIN_PULL_NONE, 0)},
    {NC, NC, 0}
};

//*** PWM ***

const PinMap PinMap_PWM[] = {
    {P1_0, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_1, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_2, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_2, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_3, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_4, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_5, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_5, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_6, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P1_6, PWM_GPT8, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_7, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_7, PWM_GPT8, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_8, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_8, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_9, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P1_9, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_10, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_11, PWM_AGT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P1_11, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_12, PWM_AGT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P1_12, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_13, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P1_14, PWM_GPT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P1_15, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_2, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P2_2, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_3, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P2_3, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_4, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_5, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P2_5, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_10, PWM_AGT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P2_11, PWM_AGT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P2_12, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P2_13, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P2_14, PWM_AGT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P3_0, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P3_1, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P3_2, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P3_3, PWM_GPT7, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P3_4, PWM_GPT7, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P3_5, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P3_6, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P3_8, PWM_AGT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P3_9, PWM_AGT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P3_11, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P3_12, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P4_0, PWM_GPT6, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_1, PWM_GPT6, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_3, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_4, PWM_GPT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_5, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_6, PWM_AGT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P4_6, PWM_GPT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_7, PWM_GPT6, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_8, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P4_8, PWM_GPT6, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_9, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P4_10, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P4_10, PWM_GPT9, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_11, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P4_11, PWM_GPT9, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P4_14, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P4_15, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P5_0, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P5_1, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P5_2, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P5_3, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P5_4, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P5_5, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {P5_11, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P5_12, PWM_GPT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P6_0, PWM_GPT6, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P6_1, PWM_GPT6, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P6_2, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P6_2, PWM_GPT7, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P6_3, PWM_GPT7, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P6_4, PWM_GPT8, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P6_5, PWM_AGT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P6_5, PWM_GPT8, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P6_8, PWM_GPT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P6_9, PWM_AGT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P6_9, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P6_10, PWM_AGT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P6_10, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P6_11, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P6_12, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P6_13, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P6_14, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P7_0, PWM_AGT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P7_0, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P7_1, PWM_AGT3, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P7_1, PWM_GPT5, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P7_2, PWM_AGT2, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P7_2, PWM_GPT6, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 0)},
    {P7_3, PWM_AGT1, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P7_3, PWM_GPT6, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_GPT1, 1)},
    {P7_4, PWM_AGT0, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P8_0, PWM_AGT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 0)},
    {P8_1, PWM_AGT4, RA_PIN_DATA_EXT(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_AGT, 1)},
    {NC, NC, 0}
};

//*** IRQ ***

const PinMap PinMap_IRQ[] = {
    {P0_0, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_1, IRQ_7, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_2, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_4, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_5, IRQ_10, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_6, IRQ_11, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_8, IRQ_12, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_9, IRQ_13, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_10, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P0_15, IRQ_13, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_0, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_1, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_4, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_5, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_10, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P1_11, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_2, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_3, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_5, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_6, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_12, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P2_13, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_1, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_2, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_4, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P3_5, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_0, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_1, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_2, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_3, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_4, IRQ_15, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_8, IRQ_7, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_9, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_10, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_11, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_14, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P4_15, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P5_1, IRQ_11, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P5_2, IRQ_12, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P5_5, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P5_6, IRQ_15, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P5_11, IRQ_15, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P5_12, IRQ_14, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P6_15, IRQ_7, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P7_6, IRQ_7, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P7_7, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P7_8, IRQ_11, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_2, IRQ_3, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_3, IRQ_2, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_4, IRQ_1, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P8_6, IRQ_0, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P9_5, IRQ_8, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P9_6, IRQ_9, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P9_7, IRQ_10, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P9_8, IRQ_11, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P10_8, IRQ_6, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P10_9, IRQ_5, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {P10_10, IRQ_4, RA_PIN_DATA(RA_PIN_MODE_IRQ, RA_PIN_PULL_NONE, 0)},
    {NC, NC, 0}
};

//*** SERIAL ***

const PinMap PinMap_UART_RX[] = {
    {P1_0, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P1_4, UART_8, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P1_10, UART_9, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P1_13, UART_2, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P2_2, UART_9, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P2_6, UART_4, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P2_12, UART_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P3_1, UART_2, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P3_4, UART_6, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P3_9, UART_3, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P3_15, UART_4, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P4_2, UART_7, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P4_8, UART_3, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P4_10, UART_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P5_2, UART_5, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P5_5, UART_6, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P5_11, UART_4, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P5_13, UART_5, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P6_1, UART_9, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P6_7, UART_8, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8)},
    {P6_14, UART_7, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P7_6, UART_3, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {P7_8, UART_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9)},
    {NC, NC, 0}
};
const PinMap PinMap_UART_TX[] = {
    {P1_1, UART_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P1_5, UART_8, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P1_9, UART_9, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P1_12, UART_2, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P2_3, UART_9, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P2_5, UART_4, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P2_7, UART_4, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P2_13, UART_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P3_2, UART_2, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P3_5, UART_6, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P3_10, UART_3, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P4_1, UART_7, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P4_9, UART_3, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P4_11, UART_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P5_1, UART_5, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P5_6, UART_6, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P5_12, UART_4, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P6_2, UART_9, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P6_13, UART_7, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P7_7, UART_3, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P8_5, UART_5, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI1_3_5_7_9, RA_PIN_SPEED_MID)},
    {P9_0, UART_4, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {P10_0, UART_8, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_UP, IOPORT_PERIPHERAL_SCI0_2_4_6_8, RA_PIN_SPEED_MID)},
    {NC, NC, 0}
};

//*** SPI ***

const PinMap PinMap_SPI_MOSI[] = {
    {P1_1, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P1_9, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P2_3, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P4_11, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P7_1, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {NC, NC, 0}
};
const PinMap PinMap_SPI_MISO[] = {
    {P1_0, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P1_10, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P2_2, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P4_10, SPI_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {P7_0, SPI_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI)},
    {NC, NC, 0}
};
const PinMap PinMap_SPI_SCLK[] = {
    {P1_2, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P1_11, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P2_4, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P4_12, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {P7_2, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_HS_HIGH)},
    {NC, NC, 0}
};
const PinMap PinMap_SPI_SSEL[] = {
    {P1_3, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_4, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_5, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_6, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_8, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P1_12, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P2_5, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P2_6, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P2_7, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P3_0, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P3_1, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P3_2, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P4_6, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P4_7, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P4_13, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P4_14, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P4_15, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P7_3, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P7_4, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P7_5, SPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {P7_8, SPI_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_SPI, RA_PIN_SPEED_MID)},
    {NC, NC, 0}
};

//*** I2C ***

const PinMap PinMap_I2C_SCL[] = {
    {P2_5, I2C_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_0, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_8, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_10, I2C_2, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_15, I2C_2, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P5_12, I2C_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {NC, NC, 0}
};
const PinMap PinMap_I2C_SDA[] = {
    {P2_6, I2C_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_1, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_7, I2C_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_9, I2C_2, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P4_14, I2C_2, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {P5_11, I2C_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_OD, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_IIC, RA_PIN_SPEED_MID_I2C)},
    {NC, NC, 0}
};

//*** CAN ***

const PinMap PinMap_CAN_RD[] = {
    {P1_2, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P1_10, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P2_2, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P4_2, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P5_11, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P6_10, CAN_1, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {P7_5, CAN_0, RA_PIN_DATA(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN)},
    {NC, NC, 0}
};
const PinMap PinMap_CAN_TD[] = {
    {P1_3, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P1_9, CAN_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P2_3, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P4_1, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P5_12, CAN_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P6_9, CAN_1, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {P7_4, CAN_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_CAN, RA_PIN_SPEED_HS_HIGH)},
    {NC, NC, 0}
};

//*** QSPI ***

const PinMap PinMap_QSPI_DATA0[] = {
    {P1_2, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P2_11, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P3_7, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P5_2, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {NC, NC, 0}
};
const PinMap PinMap_QSPI_DATA1[] = {
    {P1_1, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P2_10, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P3_8, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P5_3, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {NC, NC, 0}
};
const PinMap PinMap_QSPI_DATA2[] = {
    {P1_4, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P2_9, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P3_9, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P5_4, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {NC, NC, 0}
};
const PinMap PinMap_QSPI_DATA3[] = {
    {P1_3, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P2_8, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P3_10, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P5_5, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {NC, NC, 0}
};
const PinMap PinMap_QSPI_SCLK[] = {
    {P1_0, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P2_14, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P3_5, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P5_0, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {NC, NC, 0}
};
const PinMap PinMap_QSPI_SSEL[] = {
    {P1_12, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P2_7, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P3_6, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {P5_1, QSPI_0, RA_PIN_DATA_SPEED(RA_PIN_MODE_PERIPHERAL_PP, RA_PIN_PULL_NONE, IOPORT_PERIPHERAL_QSPI, RA_PIN_SPEED_HIGH)},
    {NC, NC, 0}
};
