/* generated vector source file - do not edit */
        #include "bsp_api.h"
        /* Do not build these data structures if no interrupts are currently allocated because IAR will have build errors. */
        #if VECTOR_DATA_IRQ_COUNT > 0
        BSP_DONT_REMOVE const fsp_vector_t g_vector_table[BSP_ICU_VECTOR_NUM_ENTRIES] BSP_PLACE_IN_SECTION(BSP_SECTION_APPLICATION_VECTORS) =
        {
                        [0] = gpt_counter_overflow_isr, /* GPT1 COUNTER OVERFLOW (Overflow) */
            [1] = gpt_capture_compare_a_isr, /* GPT1 CAPTURE COMPARE A (Capture/Compare match A) */
            [2] = r_icu_isr, /* ICU IRQ0 (External pin interrupt 0) */
            [3] = r_icu_isr, /* ICU IRQ1 (External pin interrupt 1) */
            [4] = r_icu_isr, /* ICU IRQ2 (External pin interrupt 2) */
            [5] = r_icu_isr, /* ICU IRQ3 (External pin interrupt 3) */
            [6] = r_icu_isr, /* ICU IRQ4 (External pin interrupt 4) */
            [7] = r_icu_isr, /* ICU IRQ5 (External pin interrupt 5) */
            [8] = r_icu_isr, /* ICU IRQ6 (External pin interrupt 6) */
            [9] = r_icu_isr, /* ICU IRQ7 (External pin interrupt 7) */
            [10] = r_icu_isr, /* ICU IRQ8 (External pin interrupt 8) */
            [11] = r_icu_isr, /* ICU IRQ9 (External pin interrupt 9) */
            [12] = r_icu_isr, /* ICU IRQ10 (External pin interrupt 10) */
            [13] = r_icu_isr, /* ICU IRQ11 (External pin interrupt 11) */
            [14] = r_icu_isr, /* ICU IRQ12 (External pin interrupt 12) */
            [15] = r_icu_isr, /* ICU IRQ13 (External pin interrupt 13) */
            [16] = r_icu_isr, /* ICU IRQ14 (External pin interrupt 14) */
            [17] = r_icu_isr, /* ICU IRQ15 (External pin interrupt 15) */
            [18] = rtc_carry_isr, /* RTC CARRY (Carry interrupt) */
            [19] = iic_master_rxi_isr, /* IIC0 RXI (Receive data full) */
            [20] = iic_master_txi_isr, /* IIC0 TXI (Transmit data empty) */
            [21] = iic_master_tei_isr, /* IIC0 TEI (Transmit end) */
            [22] = iic_master_eri_isr, /* IIC0 ERI (Transfer error) */
            [23] = iic_master_rxi_isr, /* IIC1 RXI (Receive data full) */
            [24] = iic_master_txi_isr, /* IIC1 TXI (Transmit data empty) */
            [25] = iic_master_tei_isr, /* IIC1 TEI (Transmit end) */
            [26] = iic_master_eri_isr, /* IIC1 ERI (Transfer error) */
            [27] = iic_master_rxi_isr, /* IIC2 RXI (Receive data full) */
            [28] = iic_master_txi_isr, /* IIC2 TXI (Transmit data empty) */
            [29] = iic_master_tei_isr, /* IIC2 TEI (Transmit end) */
            [30] = iic_master_eri_isr, /* IIC2 ERI (Transfer error) */
            [31] = spi_rxi_isr, /* SPI0 RXI (Receive buffer full) */
            [32] = spi_tei_isr, /* SPI0 TEI (Transmission complete event) */
            [33] = spi_eri_isr, /* SPI0 ERI (Error) */
            [34] = dmac_int_isr, /* DMAC0 INT (DMAC0 transfer end) */
            [35] = spi_rxi_isr, /* SPI1 RXI (Receive buffer full) */
            [36] = spi_tei_isr, /* SPI1 TEI (Transmission complete event) */
            [37] = spi_eri_isr, /* SPI1 ERI (Error) */
            [38] = dmac_int_isr, /* DMAC1 INT (DMAC1 transfer end) */
            [39] = sci_uart_rxi_isr, /* SCI0 RXI (Receive data full) */
            [40] = sci_uart_txi_isr, /* SCI0 TXI (Transmit data empty) */
            [41] = sci_uart_tei_isr, /* SCI0 TEI (Transmit end) */
            [42] = sci_uart_eri_isr, /* SCI0 ERI (Receive error) */
            [43] = sci_uart_rxi_isr, /* SCI1 RXI (Receive data full) */
            [44] = sci_uart_txi_isr, /* SCI1 TXI (Transmit data empty) */
            [45] = sci_uart_tei_isr, /* SCI1 TEI (Transmit end) */
            [46] = sci_uart_eri_isr, /* SCI1 ERI (Receive error) */
            [47] = sci_uart_rxi_isr, /* SCI2 RXI (Receive data full) */
            [48] = sci_uart_txi_isr, /* SCI2 TXI (Transmit data empty) */
            [49] = sci_uart_tei_isr, /* SCI2 TEI (Transmit end) */
            [50] = sci_uart_eri_isr, /* SCI2 ERI (Receive error) */
            [51] = sci_uart_rxi_isr, /* SCI3 RXI (Receive data full) */
            [52] = sci_uart_txi_isr, /* SCI3 TXI (Transmit data empty) */
            [53] = sci_uart_tei_isr, /* SCI3 TEI (Transmit end) */
            [54] = sci_uart_eri_isr, /* SCI3 ERI (Receive error) */
            [55] = sci_uart_rxi_isr, /* SCI4 RXI (Receive data full) */
            [56] = sci_uart_txi_isr, /* SCI4 TXI (Transmit data empty) */
            [57] = sci_uart_tei_isr, /* SCI4 TEI (Transmit end) */
            [58] = sci_uart_eri_isr, /* SCI4 ERI (Receive error) */
            [59] = sci_uart_rxi_isr, /* SCI5 RXI (Receive data full) */
            [60] = sci_uart_txi_isr, /* SCI5 TXI (Transmit data empty) */
            [61] = sci_uart_tei_isr, /* SCI5 TEI (Transmit end) */
            [62] = sci_uart_eri_isr, /* SCI5 ERI (Receive error) */
            [63] = sci_uart_rxi_isr, /* SCI6 RXI (Receive data full) */
            [64] = sci_uart_txi_isr, /* SCI6 TXI (Transmit data empty) */
            [65] = sci_uart_tei_isr, /* SCI6 TEI (Transmit end) */
            [66] = sci_uart_eri_isr, /* SCI6 ERI (Receive error) */
            [67] = sci_uart_rxi_isr, /* SCI7 RXI (Receive data full) */
            [68] = sci_uart_txi_isr, /* SCI7 TXI (Transmit data empty) */
            [69] = sci_uart_tei_isr, /* SCI7 TEI (Transmit end) */
            [70] = sci_uart_eri_isr, /* SCI7 ERI (Receive error) */
            [71] = sci_uart_rxi_isr, /* SCI8 RXI (Receive data full) */
            [72] = sci_uart_txi_isr, /* SCI8 TXI (Transmit data empty) */
            [73] = sci_uart_tei_isr, /* SCI8 TEI (Transmit end) */
            [74] = sci_uart_eri_isr, /* SCI8 ERI (Receive error) */
            [75] = sci_uart_rxi_isr, /* SCI9 RXI (Receive data full) */
            [76] = sci_uart_txi_isr, /* SCI9 TXI (Transmit data empty) */
            [77] = sci_uart_tei_isr, /* SCI9 TEI (Transmit end) */
            [78] = sci_uart_eri_isr, /* SCI9 ERI (Receive error) */
            [79] = fcu_frdyi_isr, /* FCU FRDYI (Flash ready interrupt) */
            [80] = fcu_fiferr_isr, /* FCU FIFERR (Flash access error interrupt) */
            [81] = canfd_error_isr, /* CAN0 CHERR (Channel  error) */
            [82] = canfd_channel_tx_isr, /* CAN0 TX (Transmit interrupt) */
            [83] = canfd_common_fifo_rx_isr, /* CAN0 COMFRX (Common FIFO receive interrupt) */
            [84] = canfd_error_isr, /* CAN GLERR (Global error) */
            [85] = canfd_rx_fifo_isr, /* CAN RXF (Global receive FIFO interrupt) */
            [86] = canfd_error_isr, /* CAN1 CHERR (Channel  error) */
            [87] = canfd_channel_tx_isr, /* CAN1 TX (Transmit interrupt) */
            [88] = canfd_common_fifo_rx_isr, /* CAN1 COMFRX (Common FIFO receive interrupt) */
        };
        #if BSP_FEATURE_ICU_HAS_IELSR
        const bsp_interrupt_event_t g_interrupt_event_link_select[BSP_ICU_VECTOR_NUM_ENTRIES] =
        {
            [0] = BSP_PRV_VECT_ENUM(EVENT_GPT1_COUNTER_OVERFLOW,GROUP0), /* GPT1 COUNTER OVERFLOW (Overflow) */
            [1] = BSP_PRV_VECT_ENUM(EVENT_GPT1_CAPTURE_COMPARE_A,GROUP1), /* GPT1 CAPTURE COMPARE A (Capture/Compare match A) */
            [2] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ0,GROUP2), /* ICU IRQ0 (External pin interrupt 0) */
            [3] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ1,GROUP3), /* ICU IRQ1 (External pin interrupt 1) */
            [4] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ2,GROUP4), /* ICU IRQ2 (External pin interrupt 2) */
            [5] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ3,GROUP5), /* ICU IRQ3 (External pin interrupt 3) */
            [6] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ4,GROUP6), /* ICU IRQ4 (External pin interrupt 4) */
            [7] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ5,GROUP7), /* ICU IRQ5 (External pin interrupt 5) */
            [8] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ6,GROUP0), /* ICU IRQ6 (External pin interrupt 6) */
            [9] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ7,GROUP1), /* ICU IRQ7 (External pin interrupt 7) */
            [10] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ8,GROUP2), /* ICU IRQ8 (External pin interrupt 8) */
            [11] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ9,GROUP3), /* ICU IRQ9 (External pin interrupt 9) */
            [12] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ10,GROUP4), /* ICU IRQ10 (External pin interrupt 10) */
            [13] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ11,GROUP5), /* ICU IRQ11 (External pin interrupt 11) */
            [14] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ12,GROUP6), /* ICU IRQ12 (External pin interrupt 12) */
            [15] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ13,GROUP7), /* ICU IRQ13 (External pin interrupt 13) */
            [16] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ14,GROUP0), /* ICU IRQ14 (External pin interrupt 14) */
            [17] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ15,GROUP1), /* ICU IRQ15 (External pin interrupt 15) */
            [18] = BSP_PRV_VECT_ENUM(EVENT_RTC_CARRY,GROUP2), /* RTC CARRY (Carry interrupt) */
            [19] = BSP_PRV_VECT_ENUM(EVENT_IIC0_RXI,GROUP3), /* IIC0 RXI (Receive data full) */
            [20] = BSP_PRV_VECT_ENUM(EVENT_IIC0_TXI,GROUP4), /* IIC0 TXI (Transmit data empty) */
            [21] = BSP_PRV_VECT_ENUM(EVENT_IIC0_TEI,GROUP5), /* IIC0 TEI (Transmit end) */
            [22] = BSP_PRV_VECT_ENUM(EVENT_IIC0_ERI,GROUP6), /* IIC0 ERI (Transfer error) */
            [23] = BSP_PRV_VECT_ENUM(EVENT_IIC1_RXI,GROUP7), /* IIC1 RXI (Receive data full) */
            [24] = BSP_PRV_VECT_ENUM(EVENT_IIC1_TXI,GROUP0), /* IIC1 TXI (Transmit data empty) */
            [25] = BSP_PRV_VECT_ENUM(EVENT_IIC1_TEI,GROUP1), /* IIC1 TEI (Transmit end) */
            [26] = BSP_PRV_VECT_ENUM(EVENT_IIC1_ERI,GROUP2), /* IIC1 ERI (Transfer error) */
            [27] = BSP_PRV_VECT_ENUM(EVENT_IIC2_RXI,GROUP3), /* IIC2 RXI (Receive data full) */
            [28] = BSP_PRV_VECT_ENUM(EVENT_IIC2_TXI,GROUP4), /* IIC2 TXI (Transmit data empty) */
            [29] = BSP_PRV_VECT_ENUM(EVENT_IIC2_TEI,GROUP5), /* IIC2 TEI (Transmit end) */
            [30] = BSP_PRV_VECT_ENUM(EVENT_IIC2_ERI,GROUP6), /* IIC2 ERI (Transfer error) */
            [31] = BSP_PRV_VECT_ENUM(EVENT_SPI0_RXI,GROUP7), /* SPI0 RXI (Receive buffer full) */
            [32] = BSP_PRV_VECT_ENUM(EVENT_SPI0_TEI,FIXED), /* SPI0 TEI (Transmission complete event) */
            [33] = BSP_PRV_VECT_ENUM(EVENT_SPI0_ERI,FIXED), /* SPI0 ERI (Error) */
            [34] = BSP_PRV_VECT_ENUM(EVENT_DMAC0_INT,FIXED), /* DMAC0 INT (DMAC0 transfer end) */
            [35] = BSP_PRV_VECT_ENUM(EVENT_SPI1_RXI,FIXED), /* SPI1 RXI (Receive buffer full) */
            [36] = BSP_PRV_VECT_ENUM(EVENT_SPI1_TEI,FIXED), /* SPI1 TEI (Transmission complete event) */
            [37] = BSP_PRV_VECT_ENUM(EVENT_SPI1_ERI,FIXED), /* SPI1 ERI (Error) */
            [38] = BSP_PRV_VECT_ENUM(EVENT_DMAC1_INT,FIXED), /* DMAC1 INT (DMAC1 transfer end) */
            [39] = BSP_PRV_VECT_ENUM(EVENT_SCI0_RXI,FIXED), /* SCI0 RXI (Receive data full) */
            [40] = BSP_PRV_VECT_ENUM(EVENT_SCI0_TXI,FIXED), /* SCI0 TXI (Transmit data empty) */
            [41] = BSP_PRV_VECT_ENUM(EVENT_SCI0_TEI,FIXED), /* SCI0 TEI (Transmit end) */
            [42] = BSP_PRV_VECT_ENUM(EVENT_SCI0_ERI,FIXED), /* SCI0 ERI (Receive error) */
            [43] = BSP_PRV_VECT_ENUM(EVENT_SCI1_RXI,FIXED), /* SCI1 RXI (Receive data full) */
            [44] = BSP_PRV_VECT_ENUM(EVENT_SCI1_TXI,FIXED), /* SCI1 TXI (Transmit data empty) */
            [45] = BSP_PRV_VECT_ENUM(EVENT_SCI1_TEI,FIXED), /* SCI1 TEI (Transmit end) */
            [46] = BSP_PRV_VECT_ENUM(EVENT_SCI1_ERI,FIXED), /* SCI1 ERI (Receive error) */
            [47] = BSP_PRV_VECT_ENUM(EVENT_SCI2_RXI,FIXED), /* SCI2 RXI (Receive data full) */
            [48] = BSP_PRV_VECT_ENUM(EVENT_SCI2_TXI,FIXED), /* SCI2 TXI (Transmit data empty) */
            [49] = BSP_PRV_VECT_ENUM(EVENT_SCI2_TEI,FIXED), /* SCI2 TEI (Transmit end) */
            [50] = BSP_PRV_VECT_ENUM(EVENT_SCI2_ERI,FIXED), /* SCI2 ERI (Receive error) */
            [51] = BSP_PRV_VECT_ENUM(EVENT_SCI3_RXI,FIXED), /* SCI3 RXI (Receive data full) */
            [52] = BSP_PRV_VECT_ENUM(EVENT_SCI3_TXI,FIXED), /* SCI3 TXI (Transmit data empty) */
            [53] = BSP_PRV_VECT_ENUM(EVENT_SCI3_TEI,FIXED), /* SCI3 TEI (Transmit end) */
            [54] = BSP_PRV_VECT_ENUM(EVENT_SCI3_ERI,FIXED), /* SCI3 ERI (Receive error) */
            [55] = BSP_PRV_VECT_ENUM(EVENT_SCI4_RXI,FIXED), /* SCI4 RXI (Receive data full) */
            [56] = BSP_PRV_VECT_ENUM(EVENT_SCI4_TXI,FIXED), /* SCI4 TXI (Transmit data empty) */
            [57] = BSP_PRV_VECT_ENUM(EVENT_SCI4_TEI,FIXED), /* SCI4 TEI (Transmit end) */
            [58] = BSP_PRV_VECT_ENUM(EVENT_SCI4_ERI,FIXED), /* SCI4 ERI (Receive error) */
            [59] = BSP_PRV_VECT_ENUM(EVENT_SCI5_RXI,FIXED), /* SCI5 RXI (Receive data full) */
            [60] = BSP_PRV_VECT_ENUM(EVENT_SCI5_TXI,FIXED), /* SCI5 TXI (Transmit data empty) */
            [61] = BSP_PRV_VECT_ENUM(EVENT_SCI5_TEI,FIXED), /* SCI5 TEI (Transmit end) */
            [62] = BSP_PRV_VECT_ENUM(EVENT_SCI5_ERI,FIXED), /* SCI5 ERI (Receive error) */
            [63] = BSP_PRV_VECT_ENUM(EVENT_SCI6_RXI,FIXED), /* SCI6 RXI (Receive data full) */
            [64] = BSP_PRV_VECT_ENUM(EVENT_SCI6_TXI,FIXED), /* SCI6 TXI (Transmit data empty) */
            [65] = BSP_PRV_VECT_ENUM(EVENT_SCI6_TEI,FIXED), /* SCI6 TEI (Transmit end) */
            [66] = BSP_PRV_VECT_ENUM(EVENT_SCI6_ERI,FIXED), /* SCI6 ERI (Receive error) */
            [67] = BSP_PRV_VECT_ENUM(EVENT_SCI7_RXI,FIXED), /* SCI7 RXI (Receive data full) */
            [68] = BSP_PRV_VECT_ENUM(EVENT_SCI7_TXI,FIXED), /* SCI7 TXI (Transmit data empty) */
            [69] = BSP_PRV_VECT_ENUM(EVENT_SCI7_TEI,FIXED), /* SCI7 TEI (Transmit end) */
            [70] = BSP_PRV_VECT_ENUM(EVENT_SCI7_ERI,FIXED), /* SCI7 ERI (Receive error) */
            [71] = BSP_PRV_VECT_ENUM(EVENT_SCI8_RXI,FIXED), /* SCI8 RXI (Receive data full) */
            [72] = BSP_PRV_VECT_ENUM(EVENT_SCI8_TXI,FIXED), /* SCI8 TXI (Transmit data empty) */
            [73] = BSP_PRV_VECT_ENUM(EVENT_SCI8_TEI,FIXED), /* SCI8 TEI (Transmit end) */
            [74] = BSP_PRV_VECT_ENUM(EVENT_SCI8_ERI,FIXED), /* SCI8 ERI (Receive error) */
            [75] = BSP_PRV_VECT_ENUM(EVENT_SCI9_RXI,FIXED), /* SCI9 RXI (Receive data full) */
            [76] = BSP_PRV_VECT_ENUM(EVENT_SCI9_TXI,FIXED), /* SCI9 TXI (Transmit data empty) */
            [77] = BSP_PRV_VECT_ENUM(EVENT_SCI9_TEI,FIXED), /* SCI9 TEI (Transmit end) */
            [78] = BSP_PRV_VECT_ENUM(EVENT_SCI9_ERI,FIXED), /* SCI9 ERI (Receive error) */
            [79] = BSP_PRV_VECT_ENUM(EVENT_FCU_FRDYI,FIXED), /* FCU FRDYI (Flash ready interrupt) */
            [80] = BSP_PRV_VECT_ENUM(EVENT_FCU_FIFERR,FIXED), /* FCU FIFERR (Flash access error interrupt) */
            [81] = BSP_PRV_VECT_ENUM(EVENT_CAN0_CHERR,FIXED), /* CAN0 CHERR (Channel  error) */
            [82] = BSP_PRV_VECT_ENUM(EVENT_CAN0_TX,FIXED), /* CAN0 TX (Transmit interrupt) */
            [83] = BSP_PRV_VECT_ENUM(EVENT_CAN0_COMFRX,FIXED), /* CAN0 COMFRX (Common FIFO receive interrupt) */
            [84] = BSP_PRV_VECT_ENUM(EVENT_CAN_GLERR,FIXED), /* CAN GLERR (Global error) */
            [85] = BSP_PRV_VECT_ENUM(EVENT_CAN_RXF,FIXED), /* CAN RXF (Global receive FIFO interrupt) */
            [86] = BSP_PRV_VECT_ENUM(EVENT_CAN1_CHERR,FIXED), /* CAN1 CHERR (Channel  error) */
            [87] = BSP_PRV_VECT_ENUM(EVENT_CAN1_TX,FIXED), /* CAN1 TX (Transmit interrupt) */
            [88] = BSP_PRV_VECT_ENUM(EVENT_CAN1_COMFRX,FIXED), /* CAN1 COMFRX (Common FIFO receive interrupt) */
        };
        #endif
        #endif